"use client";
import { useEffect, useMemo, useRef, useState } from "react";

type SetRow={id:number;reps:number;weight:number;done:boolean};
type Exercise={id:number;name:string;note:string;sets:SetRow[]};
const starter:Exercise[]=[
 {id:1,name:"Barbell back squat",note:"Main lift · Quads + glutes",sets:[{id:1,reps:8,weight:185,done:true},{id:2,reps:8,weight:185,done:true},{id:3,reps:8,weight:190,done:false}]},
 {id:2,name:"Romanian deadlift",note:"Hamstrings · Controlled eccentric",sets:[{id:4,reps:10,weight:135,done:false},{id:5,reps:10,weight:135,done:false},{id:6,reps:10,weight:135,done:false}]}
];
const week=[64,38,82,50,92,70,28];
type HistoryRow={id:number;name:string;muscle_group:string;exercises:string;completed_sets:number;total_sets:number;volume:number;workout_date:string};
type Profile={id:number;name:string;level:string;goal:string;units:string;weeklyDays:number};
type PlanDay={id:number;day:string;name:string;focus:string};

export default function Home(){
 const [tab,setTab]=useState<"workout"|"progress"|"plan"|"profile">("workout");
 const [exercises,setExercises]=useState(starter); const [showAdd,setShowAdd]=useState(false); const [showCoach,setShowCoach]=useState(false); const [name,setName]=useState(""); const [toast,setToast]=useState("");
 const [saveState,setSaveState]=useState<"loading"|"saving"|"saved"|"error">("loading"); const [history,setHistory]=useState<HistoryRow[]>([]); const [editingId,setEditingId]=useState<number|null>(null); const loaded=useRef(false); const currentBeforeEdit=useRef<Exercise[]|null>(null);
 const [profile,setProfile]=useState<Profile>({id:1,name:"Sam Johnson",level:"Intermediate",goal:"Build strength",units:"lb",weeklyDays:4}); const [profiles,setProfiles]=useState<Profile[]>([]); const [showProfiles,setShowProfiles]=useState(false); const [newProfileName,setNewProfileName]=useState(""); const [coachInput,setCoachInput]=useState(""); const [coachAnswer,setCoachAnswer]=useState("Ask me about today’s exercises, training volume, recovery, or what weight to use next.");
 const [planName,setPlanName]=useState("4-day strength split"); const [planDays,setPlanDays]=useState<PlanDay[]>([]);
 const [workoutName,setWorkoutName]=useState("Lower body strength"); const [muscleGroup,setMuscleGroup]=useState("Quads · Hamstrings · Glutes"); const [showNewWorkout,setShowNewWorkout]=useState(false); const [draftWorkoutName,setDraftWorkoutName]=useState(""); const [draftMuscleGroup,setDraftMuscleGroup]=useState("");
 const all=exercises.flatMap(e=>e.sets),completed=all.filter(s=>s.done).length,volume=useMemo(()=>all.filter(s=>s.done).reduce((n,s)=>n+s.reps*s.weight,0),[all]);
 const update=(eid:number,sid:number,key:"reps"|"weight"|"done",value:number|boolean)=>setExercises(xs=>xs.map(e=>e.id!==eid?e:{...e,sets:e.sets.map(s=>s.id!==sid?s:{...s,[key]:value})}));
 useEffect(()=>{fetch("/api/workouts").then(r=>r.json()).then(data=>{if(data.current?.exercises){try{setExercises(JSON.parse(data.current.exercises))}catch{}setWorkoutName(data.current.name||"My workout");setMuscleGroup(data.current.muscle_group||"Full body")}setHistory(data.history||[]);setSaveState("saved")}).catch(()=>setSaveState("error")).finally(()=>{loaded.current=true})},[]);
 useEffect(()=>{fetch("/api/profile").then(r=>r.json()).then(data=>{const list=(data.profiles||[]).map((p:any)=>({id:p.id,name:p.name,level:p.level,goal:p.goal,units:p.units,weeklyDays:p.weekly_days}));if(list.length){setProfiles(list);setProfile(list[0])}}).catch(()=>{})},[]);
 useEffect(()=>{fetch("/api/plan").then(r=>r.json()).then(data=>{if(data.plan){setPlanName(data.plan.name);try{setPlanDays(JSON.parse(data.plan.days))}catch{}}}).catch(()=>{})},[]);
 useEffect(()=>{if(!loaded.current)return;setSaveState("saving");const timer=setTimeout(()=>{const rows=exercises.flatMap(e=>e.sets);fetch("/api/workouts",{method:editingId?"PATCH":"PUT",headers:{"content-type":"application/json"},body:JSON.stringify({profileId:profile.id,id:editingId,name:workoutName,muscleGroup,exercises,completedSets:rows.filter(s=>s.done).length,totalSets:rows.length,volume:rows.filter(s=>s.done).reduce((n,s)=>n+s.reps*s.weight,0)})}).then(r=>{if(!r.ok)throw new Error();setSaveState("saved")}).catch(()=>setSaveState("error"))},650);return()=>clearTimeout(timer)},[exercises,editingId,profile.id,workoutName,muscleGroup]);
 async function finishWorkout(){setSaveState("saving");const response=await fetch("/api/workouts",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({profileId:profile.id,name:workoutName,muscleGroup,exercises,completedSets:completed,totalSets:all.length,volume})});if(response.ok){setSaveState("saved");setToast("Workout permanently saved to your history");const data=await fetch(`/api/workouts?profileId=${profile.id}`).then(r=>r.json());setHistory(data.history||[]);setTimeout(()=>setToast(""),3000)}else setSaveState("error")}
 function editWorkout(row:HistoryRow){try{currentBeforeEdit.current=exercises;setExercises(JSON.parse(row.exercises));setWorkoutName(row.name);setMuscleGroup(row.muscle_group);setEditingId(row.id);setTab("workout");setToast("Editing saved workout — corrections auto-save");setTimeout(()=>setToast(""),3000)}catch{setToast("This workout could not be opened")}}
 function cancelEditing(){if(currentBeforeEdit.current)setExercises(currentBeforeEdit.current);currentBeforeEdit.current=null;setEditingId(null);setTab("progress")}
 async function finishEditing(){setSaveState("saving");const rows=exercises.flatMap(e=>e.sets);const response=await fetch("/api/workouts",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({id:editingId,exercises,completedSets:rows.filter(s=>s.done).length,totalSets:rows.length,volume:rows.filter(s=>s.done).reduce((n,s)=>n+s.reps*s.weight,0)})});if(response.ok){const data=await fetch(`/api/workouts?profileId=${profile.id}`).then(r=>r.json());setHistory(data.history||[]);if(currentBeforeEdit.current)setExercises(currentBeforeEdit.current);currentBeforeEdit.current=null;setEditingId(null);setTab("progress");setSaveState("saved");setToast("Corrections saved to workout history");setTimeout(()=>setToast(""),3000)}else setSaveState("error")}
 async function saveProfile(){const response=await fetch("/api/profile",{method:"PUT",headers:{"content-type":"application/json"},body:JSON.stringify(profile)});if(response.ok)setProfiles(xs=>xs.map(x=>x.id===profile.id?profile:x));setToast(response.ok?"Profile and goals saved":"Profile could not be saved");setTimeout(()=>setToast(""),2500)}
 async function savePlan(){const response=await fetch("/api/plan",{method:"PUT",headers:{"content-type":"application/json"},body:JSON.stringify({profileId:profile.id,name:planName,days:planDays})});setToast(response.ok?"Workout split saved":"Add at least one workout day");setTimeout(()=>setToast(""),2500)}
 function updatePlanDay(id:number,key:"day"|"name"|"focus",value:string){setPlanDays(days=>days.map(day=>day.id===id?{...day,[key]:value}:day))}
 function addPlanDay(){setPlanDays(days=>[...days,{id:Date.now(),day:"Sunday",name:"New workout",focus:"Choose muscle groups"}])}
 async function switchProfile(next:Profile){setProfile(next);setShowProfiles(false);setSaveState("loading");const [w,p]=await Promise.all([fetch(`/api/workouts?profileId=${next.id}`).then(r=>r.json()),fetch(`/api/plan?profileId=${next.id}`).then(r=>r.json())]);if(w.current?.exercises){try{setExercises(JSON.parse(w.current.exercises))}catch{setExercises(starter)}setWorkoutName(w.current.name||"My workout");setMuscleGroup(w.current.muscle_group||"Full body")}else{setExercises([]);setWorkoutName("My workout");setMuscleGroup("Full body")}setHistory(w.history||[]);if(p.plan){setPlanName(p.plan.name);try{setPlanDays(JSON.parse(p.plan.days))}catch{setPlanDays([])}}setSaveState("saved");setTab("workout")}
 async function createProfile(){if(!newProfileName.trim())return;const response=await fetch("/api/profile",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({name:newProfileName})});const data=await response.json();if(data.profile){const next={id:data.profile.id,name:data.profile.name,level:data.profile.level,goal:data.profile.goal,units:data.profile.units,weeklyDays:data.profile.weekly_days};setProfiles(xs=>[...xs,next]);setNewProfileName("");switchProfile(next)}}
 async function removeProfile(id:number){const response=await fetch("/api/profile",{method:"DELETE",headers:{"content-type":"application/json"},body:JSON.stringify({id})});if(response.ok){const next=profiles.filter(x=>x.id!==id);setProfiles(next);if(profile.id===id&&next[0])switchProfile(next[0])}else{setToast("Keep at least one profile");setTimeout(()=>setToast(""),2000)}}
 function createNewWorkout(){if(!draftWorkoutName.trim())return;setWorkoutName(draftWorkoutName.trim());setMuscleGroup(draftMuscleGroup.trim()||"Full body");setExercises([]);setDraftWorkoutName("");setDraftMuscleGroup("");setShowNewWorkout(false);setTab("workout");setToast("New blank workout created — add your first exercise");setTimeout(()=>setToast(""),2500)}
 async function deleteSavedWorkout(id:number){if(!confirm("Delete this saved workout?"))return;const response=await fetch("/api/workouts",{method:"DELETE",headers:{"content-type":"application/json"},body:JSON.stringify({id,profileId:profile.id})});if(response.ok)setHistory(rows=>rows.filter(row=>row.id!==id))}
 async function clearCurrentWorkout(){if(!confirm("Delete the current workout and start over?"))return;await fetch("/api/workouts",{method:"DELETE",headers:{"content-type":"application/json"},body:JSON.stringify({current:true,profileId:profile.id})});setWorkoutName("My workout");setMuscleGroup("Full body");setExercises([]);setToast("Current workout cleared");setTimeout(()=>setToast(""),2000)}
 function askCoach(question=coachInput){const q=question.trim().toLowerCase();if(!q)return;let answer="";if(q.includes("calf"))answer="Yes—add 3 sets of standing calf raises for 10–15 reps after your main leg work. Keep 1–2 reps in reserve.";else if(q.includes("volume"))answer=`You have logged ${volume.toLocaleString()} ${profile.units} of completed volume today across ${completed} sets. That is a reasonable session so far; increase gradually, not more than about 5–10% week to week.`;else if(q.includes("weight")||q.includes("next")){const last=all.filter(s=>s.done).at(-1);answer=last?`Your last completed set was ${last.weight} ${profile.units} × ${last.reps}. If it felt controlled with 2 reps left, try ${last.weight+5} ${profile.units} next time; otherwise repeat it.`:"Complete at least one set and I’ll use it to suggest your next weight."}else if(q.includes("exercise")||q.includes("balance"))answer=`Your ${exercises.length} exercises include knee- and hip-dominant work. Add one unilateral movement, such as Bulgarian split squats, for a more balanced leg session.`;else if(q.includes("recover")||q.includes("tired")||q.includes("sore"))answer="If soreness changes your movement or pain is sharp, stop and recover. For normal fatigue, reduce today’s weight 10–15% and keep 2–3 reps in reserve.";else answer=`Based on today’s ${completed}/${all.length} completed sets, focus on controlled form and stop each set with 1–2 good reps left. Ask about weight, volume, recovery, calves, or exercise balance for a specific answer.`;setCoachAnswer(answer);setCoachInput("")}
 function addExercise(){if(!name.trim())return;const id=Date.now();setExercises(xs=>[...xs,{id,name:name.trim(),note:"Leg variation · Added by you",sets:[0,1,2].map(i=>({id:id+i,reps:10,weight:45,done:false}))}]);setName("");setShowAdd(false);setToast("Exercise added to today’s workout");setTimeout(()=>setToast(""),2500)}
 return <main className="app-shell">
  <aside className="sidebar"><div className="brand"><span>F</span>FORM <i>AI</i></div><nav>
   <button className={tab==="workout"?"active":""} onClick={()=>setTab("workout")}>◉ Today</button><button className={tab==="plan"?"active":""} onClick={()=>setTab("plan")}>▦ My plan</button><button className={tab==="progress"?"active":""} onClick={()=>setTab("progress")}>↗ Progress</button><button onClick={()=>setShowCoach(true)}>✦ AI coach</button>
  </nav><div className="premium"><small>FORM PRO</small><h3>Train smarter.<br/>Recover better.</h3><p>Adaptive plans, form analysis, and unlimited coaching.</p><button onClick={()=>setToast("Your 7-day Pro trial is ready!")}>Try Pro free</button></div><button className="profile" onClick={()=>setShowProfiles(true)}><b>{profile.name.split(" ").map(x=>x[0]).join("").slice(0,2).toUpperCase()}</b><span>{profile.name}<small>{profile.level} · Switch profile</small></span></button></aside>
  <section className="content"><header><div><small>{new Date().toLocaleDateString(undefined,{weekday:"long",month:"short",day:"numeric"}).toUpperCase()}</small><h1>{tab==="workout"?"Leg day. Let’s move.":tab==="progress"?"Your progress":tab==="profile"?"Your profile":"Your training plan"}</h1></div><div className="header-tools"><span className={`save-state ${saveState}`}>{saveState==="loading"?"Loading workout…":saveState==="saving"?"Saving…":saveState==="error"?"Save failed":"✓ Saved to cloud"}</span><button className="primary" onClick={()=>setShowCoach(true)}>✦ Ask FORM AI</button></div></header>
  {tab==="workout"&&<div className="grid"><section className="workout">{editingId&&<div className="editing-banner"><span>✎ Editing saved workout</span><button onClick={cancelEditing}>Cancel</button></div>}{!editingId&&<div className="workout-actions"><button onClick={()=>setShowNewWorkout(true)}>＋ New workout</button><button className="danger" onClick={clearCurrentWorkout}>Delete current</button></div>}<div className="workout-title"><div><small>{editingId?"CORRECTING HISTORY":"CURRENT WORKOUT"}</small><input className="workout-name-input" value={workoutName} onChange={e=>setWorkoutName(e.target.value)} aria-label="Workout name"/><input className="muscle-input" value={muscleGroup} onChange={e=>setMuscleGroup(e.target.value)} aria-label="Muscle groups"/></div><div className="score"><b>{exercises.length}</b><span>exercises</span></div></div><div className="track"><i style={{width:`${all.length?Math.max(8,completed/all.length*100):0}%`}}/></div><div className="progress"><span>{completed} of {all.length} sets complete</span><span>{volume.toLocaleString()} {profile.units} volume</span></div>
   {exercises.map((e,ei)=><article className="exercise" key={e.id}><div className="exercise-head"><b>{String(ei+1).padStart(2,"0")}</b><div><h3>{e.name}</h3><p>{e.note}</p></div><button>•••</button></div><div className="set-head"><span>SET</span><span>PREVIOUS</span><span>LB</span><span>REPS</span><span/></div>
    {e.sets.map((s,si)=><div className={`set-row ${s.done?"done":""}`} key={s.id}><b>{si+1}</b><span>{si===0&&ei===0?"180 × 8":"—"}</span><div className="stepper"><button onClick={()=>update(e.id,s.id,"weight",Math.max(0,s.weight-5))}>−</button><input aria-label="weight" value={s.weight} onChange={x=>update(e.id,s.id,"weight",+x.target.value)}/><button onClick={()=>update(e.id,s.id,"weight",s.weight+5)}>+</button></div><div className="stepper"><button onClick={()=>update(e.id,s.id,"reps",Math.max(1,s.reps-1))}>−</button><input aria-label="reps" value={s.reps} onChange={x=>update(e.id,s.id,"reps",+x.target.value)}/><button onClick={()=>update(e.id,s.id,"reps",s.reps+1)}>+</button></div><button className="check" onClick={()=>update(e.id,s.id,"done",!s.done)}>{s.done?"✓":""}</button></div>)}
    <button className="add-set" onClick={()=>setExercises(xs=>xs.map(x=>x.id!==e.id?x:{...x,sets:[...x.sets,{id:Date.now(),reps:10,weight:x.sets.at(-1)?.weight||45,done:false}]}))}>＋ Add set</button></article>)}
   <button className="add-exercise" onClick={()=>setShowAdd(true)}>＋ Add exercise variation</button><button className="finish-workout" onClick={editingId?finishEditing:finishWorkout}>✓ {editingId?"Save corrections":"Finish & save workout"}</button></section>
   <aside className="insights"><div className="coach-card"><div><b>✦</b><small>FORM AI COACH</small><em>LIVE</em></div><h3>Great exercise selection.</h3><p>Your squat + RDL pairing covers both knee and hip-dominant patterns. Add one single-leg movement for better balance.</p><button onClick={()=>{setName("Bulgarian split squat");setShowAdd(true)}}>＋ Add Bulgarian split squat</button><small>Based on your last 6 workouts</small></div><div className="stats"><div><small>WEEKLY VOLUME</small><b>24.8k <i>lb</i></b><em>↑ 8.4%</em></div><div><small>WORKOUT STREAK</small><b>12 <i>days</i></b><em>Personal best</em></div></div><div className="weekly"><div><span><small>TRAINING LOAD</small><h3>This week</h3></span><b>Optimal</b></div><div className="bars">{week.map((h,i)=><i key={i} style={{height:`${h}%`}} className={i===4?"hot":""}><span>{"MTWTFSS"[i]}</span></i>)}</div><p>● You’re in your productive range</p></div><div className="recovery"><small>RECOVERY CHECK</small><div><b>84</b><span>Ready to train hard<small>Sleep 8h 12m · HRV +6%</small></span></div></div></aside></div>}
  {tab==="progress"&&<div className="empty"><b>↗</b><h2>Your saved workouts</h2><p>Every finished workout is stored here and synced across your phone and dashboard.</p><div className="history-list">{history.length?history.map(row=><article key={row.id}><div><strong>{row.name}</strong><span>{new Date(row.workout_date+"T12:00:00").toLocaleDateString(undefined,{month:"short",day:"numeric",year:"numeric"})} · {row.muscle_group}</span></div><b>{row.volume.toLocaleString()} <small>{profile.units}</small></b><em>{row.completed_sets}/{row.total_sets} sets</em><button onClick={()=>editWorkout(row)}>✎ Edit</button><button className="delete-history" onClick={()=>deleteSavedWorkout(row.id)}>Delete</button></article>):<div className="no-history">Finish your first workout to see it here.</div>}</div><button className="primary new-from-history" onClick={()=>setShowNewWorkout(true)}>＋ Create a new workout</button></div>}
  {tab==="plan"&&<div className="plan-page"><div className="plan-heading"><div><small>WORKOUT SPLIT</small><input aria-label="Plan name" value={planName} onChange={e=>setPlanName(e.target.value)}/><p>Edit your training days and muscle-group focus. Changes save to mobile and desktop.</p></div><button className="primary" onClick={savePlan}>Save split</button></div><div className="plan-days">{planDays.map((day,index)=><article key={day.id}><div className="day-number">{String(index+1).padStart(2,"0")}</div><label>Day<select value={day.day} onChange={e=>updatePlanDay(day.id,"day",e.target.value)}>{["Monday","Tuesday","Wednesday","Thursday","Friday","Saturday","Sunday"].map(x=><option key={x}>{x}</option>)}</select></label><label>Workout name<input value={day.name} onChange={e=>updatePlanDay(day.id,"name",e.target.value)}/></label><label>Muscle focus<input value={day.focus} onChange={e=>updatePlanDay(day.id,"focus",e.target.value)}/></label><button className="remove-day" onClick={()=>setPlanDays(days=>days.filter(x=>x.id!==day.id))}>Remove</button></article>)}</div><button className="add-plan-day" onClick={addPlanDay}>＋ Add workout day</button></div>}
  {tab==="profile"&&<div className="profile-page"><div className="profile-hero"><div>{profile.name.split(" ").map(x=>x[0]).join("").slice(0,2).toUpperCase()}</div><span><small>TRAINING PROFILE</small><h2>{profile.name}</h2><p>{profile.goal} · {profile.weeklyDays} days per week</p></span><button className="switch-profile" onClick={()=>setShowProfiles(true)}>Switch profile</button></div><div className="profile-form"><label>Display name<input value={profile.name} onChange={e=>setProfile({...profile,name:e.target.value})}/></label><label>Experience<select value={profile.level} onChange={e=>setProfile({...profile,level:e.target.value})}><option>Beginner</option><option>Intermediate</option><option>Advanced</option></select></label><label>Primary goal<select value={profile.goal} onChange={e=>setProfile({...profile,goal:e.target.value})}><option>Build strength</option><option>Build muscle</option><option>Lose fat</option><option>General fitness</option></select></label><label>Weight units<select value={profile.units} onChange={e=>setProfile({...profile,units:e.target.value})}><option value="lb">Pounds (lb)</option><option value="kg">Kilograms (kg)</option></select></label><label>Training days per week<input type="number" min="1" max="7" value={profile.weeklyDays} onChange={e=>setProfile({...profile,weeklyDays:+e.target.value})}/></label><button className="primary" onClick={saveProfile}>Save profile</button></div><div className="install-card"><b>iPhone app — free</b><p>Open this site in Safari, tap Share, then “Add to Home Screen.” FORM AI opens full-screen like an app with no App Store fee.</p></div></div>}
  </section>
  <nav className="mobile"><button onClick={()=>setTab("workout")}>◉<span>Today</span></button><button onClick={()=>setTab("plan")}>▦<span>Plan</span></button><button className="fab" onClick={()=>setShowCoach(true)}>✦</button><button onClick={()=>setTab("progress")}>↗<span>Progress</span></button><button onClick={()=>setShowProfiles(true)}>○<span>Profiles</span></button></nav>
  {showNewWorkout&&<div className="backdrop" onMouseDown={()=>setShowNewWorkout(false)}><div className="modal" onMouseDown={e=>e.stopPropagation()}><button className="close" onClick={()=>setShowNewWorkout(false)}>×</button><small>NEW WORKOUT</small><h2>Build anything you want.</h2><p>Start blank, then add exercises, sets, reps, and weights.</p><label>Workout name<input autoFocus placeholder="e.g. Push day" value={draftWorkoutName} onChange={e=>setDraftWorkoutName(e.target.value)}/></label><label>Muscle focus<input placeholder="e.g. Chest · Shoulders · Triceps" value={draftMuscleGroup} onChange={e=>setDraftMuscleGroup(e.target.value)} onKeyDown={e=>e.key==="Enter"&&createNewWorkout()}/></label><div className="chips">{["Push day","Pull day","Full body","Cardio + core"].map(x=><button key={x} onClick={()=>setDraftWorkoutName(x)}>{x}</button>)}</div><button className="primary full" onClick={createNewWorkout}>Create blank workout</button></div></div>}
  {showAdd&&<div className="backdrop" onMouseDown={()=>setShowAdd(false)}><div className="modal" onMouseDown={e=>e.stopPropagation()}><button className="close" onClick={()=>setShowAdd(false)}>×</button><small>ADD AN EXERCISE</small><h2>What exercise are you doing?</h2><p>Add any movement to {workoutName}.</p><label>Exercise name<input autoFocus placeholder="e.g. Dumbbell bench press" value={name} onChange={e=>setName(e.target.value)} onKeyDown={e=>e.key==="Enter"&&addExercise()}/></label><div className="chips">{["Bench press","Lat pulldown","Goblet squat","Cable row"].map(x=><button key={x} onClick={()=>setName(x)}>{x}</button>)}</div><button className="primary full" onClick={addExercise}>Add 3 sets to workout</button></div></div>}
  {showCoach&&<aside className="drawer"><button className="close" onClick={()=>setShowCoach(false)}>×</button><b className="spark">✦</b><small>FORM AI · WORKOUT AWARE</small><h2>Your personal strength coach</h2><div className="message"><b>Coach response</b><p>{coachAnswer}</p></div><div className="quick"><button onClick={()=>askCoach("Should I add calves?")}>Should I add calves?</button><button onClick={()=>askCoach("Check my weekly volume")}>Check my workout volume</button><button onClick={()=>askCoach("Suggest my next weight")}>Suggest my next weight</button></div><div className="chat"><input value={coachInput} onChange={e=>setCoachInput(e.target.value)} onKeyDown={e=>e.key==="Enter"&&askCoach()} placeholder="Ask about your workout…"/><button onClick={()=>askCoach()}>↑</button></div></aside>}
  {showProfiles&&<div className="profile-gate"><button className="close" onClick={()=>setShowProfiles(false)}>×</button><small>FORM AI FAMILY</small><h2>Who’s training?</h2><p>Each profile has its own workout split, current workout, goals, and saved history.</p><div className="profile-choices">{profiles.map((p,i)=><article key={p.id} className={p.id===profile.id?"selected":""}><button className="profile-choice" onClick={()=>switchProfile(p)}><b style={{background:["#6366f1","#0891b2","#db2777","#059669"][i%4]}}>{p.name.split(" ").map(x=>x[0]).join("").slice(0,2).toUpperCase()}</b><span>{p.name}<small>{p.goal}</small></span></button>{profiles.length>1&&<button className="delete-profile" onClick={()=>removeProfile(p.id)}>Remove</button>}</article>)}</div><div className="new-profile"><input value={newProfileName} onChange={e=>setNewProfileName(e.target.value)} onKeyDown={e=>e.key==="Enter"&&createProfile()} placeholder="New profile name"/><button onClick={createProfile}>＋ Add profile</button></div></div>}
  {toast&&<div className="toast">✓ {toast}</div>}
 </main>
}
