"use client";
import { useEffect, useMemo, useRef, useState } from "react";

type SetRow={id:number;reps:number;weight:number;done:boolean};
type Exercise={id:number;name:string;note:string;sets:SetRow[]};
const starter:Exercise[]=[
 {id:1,name:"Barbell back squat",note:"Main lift · Quads + glutes",sets:[{id:1,reps:8,weight:185,done:true},{id:2,reps:8,weight:185,done:true},{id:3,reps:8,weight:190,done:false}]},
 {id:2,name:"Romanian deadlift",note:"Hamstrings · Controlled eccentric",sets:[{id:4,reps:10,weight:135,done:false},{id:5,reps:10,weight:135,done:false},{id:6,reps:10,weight:135,done:false}]}
];
const week=[64,38,82,50,92,70,28];
type HistoryRow={id:number;name:string;muscle_group:string;exercises:string;completed_sets:number;total_sets:number;volume:number;workout_date:string};

export default function Home(){
 const [tab,setTab]=useState<"workout"|"progress"|"plan">("workout");
 const [exercises,setExercises]=useState(starter); const [showAdd,setShowAdd]=useState(false); const [showCoach,setShowCoach]=useState(false); const [name,setName]=useState(""); const [toast,setToast]=useState("");
 const [saveState,setSaveState]=useState<"loading"|"saving"|"saved"|"error">("loading"); const [history,setHistory]=useState<HistoryRow[]>([]); const [editingId,setEditingId]=useState<number|null>(null); const loaded=useRef(false); const currentBeforeEdit=useRef<Exercise[]|null>(null);
 const all=exercises.flatMap(e=>e.sets),completed=all.filter(s=>s.done).length,volume=useMemo(()=>all.filter(s=>s.done).reduce((n,s)=>n+s.reps*s.weight,0),[all]);
 const update=(eid:number,sid:number,key:"reps"|"weight"|"done",value:number|boolean)=>setExercises(xs=>xs.map(e=>e.id!==eid?e:{...e,sets:e.sets.map(s=>s.id!==sid?s:{...s,[key]:value})}));
 useEffect(()=>{fetch("/api/workouts").then(r=>r.json()).then(data=>{if(data.current?.exercises){try{setExercises(JSON.parse(data.current.exercises))}catch{}}setHistory(data.history||[]);setSaveState("saved")}).catch(()=>setSaveState("error")).finally(()=>{loaded.current=true})},[]);
 useEffect(()=>{if(!loaded.current)return;setSaveState("saving");const timer=setTimeout(()=>{const rows=exercises.flatMap(e=>e.sets);fetch("/api/workouts",{method:editingId?"PATCH":"PUT",headers:{"content-type":"application/json"},body:JSON.stringify({id:editingId,exercises,completedSets:rows.filter(s=>s.done).length,totalSets:rows.length,volume:rows.filter(s=>s.done).reduce((n,s)=>n+s.reps*s.weight,0)})}).then(r=>{if(!r.ok)throw new Error();setSaveState("saved")}).catch(()=>setSaveState("error"))},650);return()=>clearTimeout(timer)},[exercises,editingId]);
 async function finishWorkout(){setSaveState("saving");const response=await fetch("/api/workouts",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({exercises,completedSets:completed,totalSets:all.length,volume})});if(response.ok){setSaveState("saved");setToast("Workout permanently saved to your history");const data=await fetch("/api/workouts").then(r=>r.json());setHistory(data.history||[]);setTimeout(()=>setToast(""),3000)}else setSaveState("error")}
 function editWorkout(row:HistoryRow){try{currentBeforeEdit.current=exercises;setExercises(JSON.parse(row.exercises));setEditingId(row.id);setTab("workout");setToast("Editing saved workout — corrections auto-save");setTimeout(()=>setToast(""),3000)}catch{setToast("This workout could not be opened")}}
 function cancelEditing(){if(currentBeforeEdit.current)setExercises(currentBeforeEdit.current);currentBeforeEdit.current=null;setEditingId(null);setTab("progress")}
 async function finishEditing(){setSaveState("saving");const rows=exercises.flatMap(e=>e.sets);const response=await fetch("/api/workouts",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({id:editingId,exercises,completedSets:rows.filter(s=>s.done).length,totalSets:rows.length,volume:rows.filter(s=>s.done).reduce((n,s)=>n+s.reps*s.weight,0)})});if(response.ok){const data=await fetch("/api/workouts").then(r=>r.json());setHistory(data.history||[]);if(currentBeforeEdit.current)setExercises(currentBeforeEdit.current);currentBeforeEdit.current=null;setEditingId(null);setTab("progress");setSaveState("saved");setToast("Corrections saved to workout history");setTimeout(()=>setToast(""),3000)}else setSaveState("error")}
 function addExercise(){if(!name.trim())return;const id=Date.now();setExercises(xs=>[...xs,{id,name:name.trim(),note:"Leg variation · Added by you",sets:[0,1,2].map(i=>({id:id+i,reps:10,weight:45,done:false}))}]);setName("");setShowAdd(false);setToast("Exercise added to today’s workout");setTimeout(()=>setToast(""),2500)}
 return <main className="app-shell">
  <aside className="sidebar"><div className="brand"><span>F</span>FORM <i>AI</i></div><nav>
   <button className={tab==="workout"?"active":""} onClick={()=>setTab("workout")}>◉ Today</button><button className={tab==="plan"?"active":""} onClick={()=>setTab("plan")}>▦ My plan</button><button className={tab==="progress"?"active":""} onClick={()=>setTab("progress")}>↗ Progress</button><button onClick={()=>setShowCoach(true)}>✦ AI coach</button>
  </nav><div className="premium"><small>FORM PRO</small><h3>Train smarter.<br/>Recover better.</h3><p>Adaptive plans, form analysis, and unlimited coaching.</p><button onClick={()=>setToast("Your 7-day Pro trial is ready!")}>Try Pro free</button></div><div className="profile"><b>SJ</b><span>Sam Johnson<small>Intermediate</small></span></div></aside>
  <section className="content"><header><div><small>{new Date().toLocaleDateString(undefined,{weekday:"long",month:"short",day:"numeric"}).toUpperCase()}</small><h1>{tab==="workout"?"Leg day. Let’s move.":tab==="progress"?"Your progress":"Your training plan"}</h1></div><div className="header-tools"><span className={`save-state ${saveState}`}>{saveState==="loading"?"Loading workout…":saveState==="saving"?"Saving…":saveState==="error"?"Save failed":"✓ Saved to cloud"}</span><button className="primary" onClick={()=>setShowCoach(true)}>✦ Ask FORM AI</button></div></header>
  {tab==="workout"&&<div className="grid"><section className="workout">{editingId&&<div className="editing-banner"><span>✎ Editing saved workout</span><button onClick={cancelEditing}>Cancel</button></div>}<div className="workout-title"><div><small>{editingId?"CORRECTING HISTORY":"TODAY’S WORKOUT"}</small><h2>Lower body strength</h2><p>Quads · Hamstrings · Glutes • 55 min</p></div><div className="score"><b>92</b><span>match</span></div></div><div className="track"><i style={{width:`${Math.max(8,completed/all.length*100)}%`}}/></div><div className="progress"><span>{completed} of {all.length} sets complete</span><span>{volume.toLocaleString()} lb volume</span></div>
   {exercises.map((e,ei)=><article className="exercise" key={e.id}><div className="exercise-head"><b>{String(ei+1).padStart(2,"0")}</b><div><h3>{e.name}</h3><p>{e.note}</p></div><button>•••</button></div><div className="set-head"><span>SET</span><span>PREVIOUS</span><span>LB</span><span>REPS</span><span/></div>
    {e.sets.map((s,si)=><div className={`set-row ${s.done?"done":""}`} key={s.id}><b>{si+1}</b><span>{si===0&&ei===0?"180 × 8":"—"}</span><div className="stepper"><button onClick={()=>update(e.id,s.id,"weight",Math.max(0,s.weight-5))}>−</button><input aria-label="weight" value={s.weight} onChange={x=>update(e.id,s.id,"weight",+x.target.value)}/><button onClick={()=>update(e.id,s.id,"weight",s.weight+5)}>+</button></div><div className="stepper"><button onClick={()=>update(e.id,s.id,"reps",Math.max(1,s.reps-1))}>−</button><input aria-label="reps" value={s.reps} onChange={x=>update(e.id,s.id,"reps",+x.target.value)}/><button onClick={()=>update(e.id,s.id,"reps",s.reps+1)}>+</button></div><button className="check" onClick={()=>update(e.id,s.id,"done",!s.done)}>{s.done?"✓":""}</button></div>)}
    <button className="add-set" onClick={()=>setExercises(xs=>xs.map(x=>x.id!==e.id?x:{...x,sets:[...x.sets,{id:Date.now(),reps:10,weight:x.sets.at(-1)?.weight||45,done:false}]}))}>＋ Add set</button></article>)}
   <button className="add-exercise" onClick={()=>setShowAdd(true)}>＋ Add exercise variation</button><button className="finish-workout" onClick={editingId?finishEditing:finishWorkout}>✓ {editingId?"Save corrections":"Finish & save workout"}</button></section>
   <aside className="insights"><div className="coach-card"><div><b>✦</b><small>FORM AI COACH</small><em>LIVE</em></div><h3>Great exercise selection.</h3><p>Your squat + RDL pairing covers both knee and hip-dominant patterns. Add one single-leg movement for better balance.</p><button onClick={()=>{setName("Bulgarian split squat");setShowAdd(true)}}>＋ Add Bulgarian split squat</button><small>Based on your last 6 workouts</small></div><div className="stats"><div><small>WEEKLY VOLUME</small><b>24.8k <i>lb</i></b><em>↑ 8.4%</em></div><div><small>WORKOUT STREAK</small><b>12 <i>days</i></b><em>Personal best</em></div></div><div className="weekly"><div><span><small>TRAINING LOAD</small><h3>This week</h3></span><b>Optimal</b></div><div className="bars">{week.map((h,i)=><i key={i} style={{height:`${h}%`}} className={i===4?"hot":""}><span>{"MTWTFSS"[i]}</span></i>)}</div><p>● You’re in your productive range</p></div><div className="recovery"><small>RECOVERY CHECK</small><div><b>84</b><span>Ready to train hard<small>Sleep 8h 12m · HRV +6%</small></span></div></div></aside></div>}
  {tab!=="workout"&&<div className="empty"><b>{tab==="progress"?"↗":"▦"}</b><h2>{tab==="progress"?"Your saved workouts":"4-day strength split"}</h2><p>{tab==="progress"?"Every finished workout is stored here and synced across your phone and dashboard.":"Lower strength today, upper push Friday, active recovery Saturday, and upper pull Sunday."}</p>{tab==="progress"?<div className="history-list">{history.length?history.map(row=><article key={row.id}><div><strong>{row.name}</strong><span>{new Date(row.workout_date+"T12:00:00").toLocaleDateString(undefined,{month:"short",day:"numeric",year:"numeric"})} · {row.muscle_group}</span></div><b>{row.volume.toLocaleString()} <small>lb</small></b><em>{row.completed_sets}/{row.total_sets} sets</em><button onClick={()=>editWorkout(row)}>✎ Edit</button></article>):<div className="no-history">Finish your first workout to see it here.</div>}</div>:<button className="primary" onClick={()=>setTab("workout")}>Open today’s workout</button>}</div>}
  </section>
  <nav className="mobile"><button onClick={()=>setTab("workout")}>◉<span>Today</span></button><button onClick={()=>setTab("plan")}>▦<span>Plan</span></button><button className="fab" onClick={()=>setShowCoach(true)}>✦</button><button onClick={()=>setTab("progress")}>↗<span>Progress</span></button><button>○<span>Profile</span></button></nav>
  {showAdd&&<div className="backdrop" onMouseDown={()=>setShowAdd(false)}><div className="modal" onMouseDown={e=>e.stopPropagation()}><button className="close" onClick={()=>setShowAdd(false)}>×</button><small>ADD A VARIATION</small><h2>What exercise are you doing?</h2><p>FORM AI will check how it fits with today’s training.</p><label>Exercise name<input autoFocus placeholder="e.g. Bulgarian split squat" value={name} onChange={e=>setName(e.target.value)} onKeyDown={e=>e.key==="Enter"&&addExercise()}/></label><div className="chips">{["Leg press","Walking lunges","Leg extension"].map(x=><button key={x} onClick={()=>setName(x)}>{x}</button>)}</div><button className="primary full" onClick={addExercise}>Add 3 sets to workout</button></div></div>}
  {showCoach&&<aside className="drawer"><button className="close" onClick={()=>setShowCoach(false)}>×</button><b className="spark">✦</b><small>FORM AI</small><h2>Your personal strength coach</h2><div className="message"><b>Today looks well balanced.</b><p>Keep the RDLs at 135 lb and use a slow 3-second lowering phase. If the last set feels below RPE 8, add 10 lb next week.</p></div><div className="quick"><button>Should I add calves?</button><button>Check my weekly volume</button><button>Suggest my next weight</button></div><div className="chat"><input placeholder="Ask about your workout…"/><button>↑</button></div></aside>}
  {toast&&<div className="toast">✓ {toast}</div>}
 </main>
}
